name: .NET Core

on: [push]

jobs:
  build:
    env:
      NUGET_KEY: ${{secrets.NUGET_LIT_NET_KEY}}

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: Publish Lit.Common nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Common\Lit.Common.csproj

    - name: Publish Lit.Names nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Names\Lit.Names.csproj

    - name: Publish Lit.Os.Win nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Os.Win\Lit.Os.Win.csproj

    - name: Publish Lit.Auditing nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Auditing\Lit.Auditing.csproj

    - name: Publish Lit.Auditing.NLog nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Auditing.NLog\Lit.Audition.NLog.csproj

    - name: Publish Lit.Db nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Db\Lit.Db.csproj

    - name: Publish Lit.Db.MySql nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Db.MySql\Lit.Db.MySql.csproj

    - name: Publish Lit.Db.Sql nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Db.Sql\Lit.Db.Sql.csproj

    - name: Publish Lit.Ui nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Ui\Lit.Ui.csproj

    - name: Publish Lit.Ui.Wpf nuget packages
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: Lit.Ui.Wpf\Lit.Ui.Wpf.csproj
